# Apache-style conf 测试样本
ServerRoot "/etc/mauimm"

Listen 8080

<VirtualHost *:8080>
    ServerName localhost
    DocumentRoot "/var/www/mauimm"
    DirectoryIndex index.html
</VirtualHost>

KeepAlive On
MaxKeepAliveRequests 100
